apiVersion: batch/v1
kind: Job
metadata:
  name: worker-%WORKER_ID%
  labels:
    jobgroup: worker
spec:
  backoffLimit: 0
  template:
    metadata:
      name: worker
      labels:
        jobgroup: worker
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: gcloud-key
      containers:
      - name: worker
        image: maven:3.5.3-jdk-8
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
        - name: WORKER_TOTAL
          value: "%WORKER_TOTAL%"
        - name: WORKER_ID
          value: "%WORKER_ID%"
        - name: ISSUES_TABLE
          value: "big_issues"
        - name: MEASURES_TABLE
          value: "big_measures"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/key.json
        command: ["sh", "-c"]
        args:
        - "curl -L \"https://github.com/saberduck/SonarJS/releases/download/kub4/shipit-dinesh.jar\" -o shipit.jar &&
           java -jar shipit.jar $WORKER_TOTAL $WORKER_ID $ISSUES_TABLE $MEASURES_TABLE;
           sleep 600
          "
        resources:
          requests:
            cpu: 0.51
      restartPolicy: Never
