apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: maven:3.5.3-jdk-8
        command: ["sh", "-c"]
        args:
        - "curl -L \"https://github.com/saberduck/SonarJS/releases/download/kub1/shipit-4.1-SNAPSHOT.jar\" -o shipit.jar &&
           java -jar shipit.jar;
           sleep 600
          "
        resources:
          requests:
            cpu: 0.51
            memory: "2G"
