apiVersion: batch/v1
kind: Job
metadata:
  name: worker-%WORKER_ID%
  labels:
    jobgroup: worker
spec:
  backoffLimit: 0
  template:
    metadata:
      name: worker
      labels:
        jobgroup: worker
    spec:
      containers:
      - name: worker
        image: maven:3.5.3-jdk-8
        env:
        - name: WORKER_ID
          value: "%WORKER_ID%"
        - name: WORKER_TOTAL
          value: "%WORKER_TOTAL%"
        - name: OUTPUT_TABLE
          value: "issues_dinesh"
        - name: GCLOUD_KEY
          valueFrom:
            secretKeyRef:
              name: gcloud
              key: key
        command: ["sh", "-c"]
        args:
        - "echo $GCLOUD_KEY > /gcloud.txt &&
           export GOOGLE_APPLICATION_CREDENTIALS=/gcloud.txt &&
           curl -L \"https://github.com/saberduck/SonarJS/releases/download/kub2/shipit-dinesh.jar\" -o shipit.jar &&
           java -jar shipit.jar $WORKER_TOTAL $WORKER_ID $OUTPUT_TABLE;
           sleep 600
          "
        resources:
          requests:
            cpu: 0.51
      restartPolicy: Never
